// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: baseFile.proto

package edu.umich.eecs.cooties;

public final class BaseFile {
  private BaseFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseFile1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int64 infectedUserId = 1;
    /**
     * <code>repeated int64 infectedUserId = 1;</code>
     */
    java.util.List<java.lang.Long> getInfectedUserIdList();
    /**
     * <code>repeated int64 infectedUserId = 1;</code>
     */
    int getInfectedUserIdCount();
    /**
     * <code>repeated int64 infectedUserId = 1;</code>
     */
    long getInfectedUserId(int index);

    // optional int32 ibeaconMajor = 2;
    /**
     * <code>optional int32 ibeaconMajor = 2;</code>
     */
    boolean hasIbeaconMajor();
    /**
     * <code>optional int32 ibeaconMajor = 2;</code>
     */
    int getIbeaconMajor();

    // optional int64 hideHealthStatus = 3;
    /**
     * <code>optional int64 hideHealthStatus = 3;</code>
     */
    boolean hasHideHealthStatus();
    /**
     * <code>optional int64 hideHealthStatus = 3;</code>
     */
    long getHideHealthStatus();

    // optional int64 incubationTimer = 4;
    /**
     * <code>optional int64 incubationTimer = 4;</code>
     */
    boolean hasIncubationTimer();
    /**
     * <code>optional int64 incubationTimer = 4;</code>
     */
    long getIncubationTimer();
  }
  /**
   * Protobuf type {@code hmc.BaseFile1}
   */
  public static final class BaseFile1 extends
      com.google.protobuf.GeneratedMessage
      implements BaseFile1OrBuilder {
    // Use BaseFile1.newBuilder() to construct.
    private BaseFile1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseFile1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseFile1 defaultInstance;
    public static BaseFile1 getDefaultInstance() {
      return defaultInstance;
    }

    public BaseFile1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseFile1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                infectedUserId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              infectedUserId_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                infectedUserId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                infectedUserId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              ibeaconMajor_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              hideHealthStatus_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              incubationTimer_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          infectedUserId_ = java.util.Collections.unmodifiableList(infectedUserId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.eecs.cooties.BaseFile.internal_static_hmc_BaseFile1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.eecs.cooties.BaseFile.internal_static_hmc_BaseFile1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umich.eecs.cooties.BaseFile.BaseFile1.class, edu.umich.eecs.cooties.BaseFile.BaseFile1.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseFile1> PARSER =
        new com.google.protobuf.AbstractParser<BaseFile1>() {
      public BaseFile1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseFile1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseFile1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated int64 infectedUserId = 1;
    public static final int INFECTEDUSERID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> infectedUserId_;
    /**
     * <code>repeated int64 infectedUserId = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getInfectedUserIdList() {
      return infectedUserId_;
    }
    /**
     * <code>repeated int64 infectedUserId = 1;</code>
     */
    public int getInfectedUserIdCount() {
      return infectedUserId_.size();
    }
    /**
     * <code>repeated int64 infectedUserId = 1;</code>
     */
    public long getInfectedUserId(int index) {
      return infectedUserId_.get(index);
    }

    // optional int32 ibeaconMajor = 2;
    public static final int IBEACONMAJOR_FIELD_NUMBER = 2;
    private int ibeaconMajor_;
    /**
     * <code>optional int32 ibeaconMajor = 2;</code>
     */
    public boolean hasIbeaconMajor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 ibeaconMajor = 2;</code>
     */
    public int getIbeaconMajor() {
      return ibeaconMajor_;
    }

    // optional int64 hideHealthStatus = 3;
    public static final int HIDEHEALTHSTATUS_FIELD_NUMBER = 3;
    private long hideHealthStatus_;
    /**
     * <code>optional int64 hideHealthStatus = 3;</code>
     */
    public boolean hasHideHealthStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 hideHealthStatus = 3;</code>
     */
    public long getHideHealthStatus() {
      return hideHealthStatus_;
    }

    // optional int64 incubationTimer = 4;
    public static final int INCUBATIONTIMER_FIELD_NUMBER = 4;
    private long incubationTimer_;
    /**
     * <code>optional int64 incubationTimer = 4;</code>
     */
    public boolean hasIncubationTimer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 incubationTimer = 4;</code>
     */
    public long getIncubationTimer() {
      return incubationTimer_;
    }

    private void initFields() {
      infectedUserId_ = java.util.Collections.emptyList();
      ibeaconMajor_ = 0;
      hideHealthStatus_ = 0L;
      incubationTimer_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < infectedUserId_.size(); i++) {
        output.writeInt64(1, infectedUserId_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, ibeaconMajor_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, hideHealthStatus_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, incubationTimer_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < infectedUserId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(infectedUserId_.get(i));
        }
        size += dataSize;
        size += 1 * getInfectedUserIdList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ibeaconMajor_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, hideHealthStatus_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, incubationTimer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.eecs.cooties.BaseFile.BaseFile1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.eecs.cooties.BaseFile.BaseFile1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hmc.BaseFile1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.eecs.cooties.BaseFile.BaseFile1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.eecs.cooties.BaseFile.internal_static_hmc_BaseFile1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.eecs.cooties.BaseFile.internal_static_hmc_BaseFile1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umich.eecs.cooties.BaseFile.BaseFile1.class, edu.umich.eecs.cooties.BaseFile.BaseFile1.Builder.class);
      }

      // Construct using edu.umich.eecs.cooties.BaseFile.BaseFile1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        infectedUserId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        ibeaconMajor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hideHealthStatus_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        incubationTimer_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.eecs.cooties.BaseFile.internal_static_hmc_BaseFile1_descriptor;
      }

      public edu.umich.eecs.cooties.BaseFile.BaseFile1 getDefaultInstanceForType() {
        return edu.umich.eecs.cooties.BaseFile.BaseFile1.getDefaultInstance();
      }

      public edu.umich.eecs.cooties.BaseFile.BaseFile1 build() {
        edu.umich.eecs.cooties.BaseFile.BaseFile1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umich.eecs.cooties.BaseFile.BaseFile1 buildPartial() {
        edu.umich.eecs.cooties.BaseFile.BaseFile1 result = new edu.umich.eecs.cooties.BaseFile.BaseFile1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          infectedUserId_ = java.util.Collections.unmodifiableList(infectedUserId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infectedUserId_ = infectedUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ibeaconMajor_ = ibeaconMajor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hideHealthStatus_ = hideHealthStatus_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.incubationTimer_ = incubationTimer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.eecs.cooties.BaseFile.BaseFile1) {
          return mergeFrom((edu.umich.eecs.cooties.BaseFile.BaseFile1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umich.eecs.cooties.BaseFile.BaseFile1 other) {
        if (other == edu.umich.eecs.cooties.BaseFile.BaseFile1.getDefaultInstance()) return this;
        if (!other.infectedUserId_.isEmpty()) {
          if (infectedUserId_.isEmpty()) {
            infectedUserId_ = other.infectedUserId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfectedUserIdIsMutable();
            infectedUserId_.addAll(other.infectedUserId_);
          }
          onChanged();
        }
        if (other.hasIbeaconMajor()) {
          setIbeaconMajor(other.getIbeaconMajor());
        }
        if (other.hasHideHealthStatus()) {
          setHideHealthStatus(other.getHideHealthStatus());
        }
        if (other.hasIncubationTimer()) {
          setIncubationTimer(other.getIncubationTimer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umich.eecs.cooties.BaseFile.BaseFile1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umich.eecs.cooties.BaseFile.BaseFile1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int64 infectedUserId = 1;
      private java.util.List<java.lang.Long> infectedUserId_ = java.util.Collections.emptyList();
      private void ensureInfectedUserIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          infectedUserId_ = new java.util.ArrayList<java.lang.Long>(infectedUserId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 infectedUserId = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getInfectedUserIdList() {
        return java.util.Collections.unmodifiableList(infectedUserId_);
      }
      /**
       * <code>repeated int64 infectedUserId = 1;</code>
       */
      public int getInfectedUserIdCount() {
        return infectedUserId_.size();
      }
      /**
       * <code>repeated int64 infectedUserId = 1;</code>
       */
      public long getInfectedUserId(int index) {
        return infectedUserId_.get(index);
      }
      /**
       * <code>repeated int64 infectedUserId = 1;</code>
       */
      public Builder setInfectedUserId(
          int index, long value) {
        ensureInfectedUserIdIsMutable();
        infectedUserId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 infectedUserId = 1;</code>
       */
      public Builder addInfectedUserId(long value) {
        ensureInfectedUserIdIsMutable();
        infectedUserId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 infectedUserId = 1;</code>
       */
      public Builder addAllInfectedUserId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureInfectedUserIdIsMutable();
        super.addAll(values, infectedUserId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 infectedUserId = 1;</code>
       */
      public Builder clearInfectedUserId() {
        infectedUserId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // optional int32 ibeaconMajor = 2;
      private int ibeaconMajor_ ;
      /**
       * <code>optional int32 ibeaconMajor = 2;</code>
       */
      public boolean hasIbeaconMajor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 ibeaconMajor = 2;</code>
       */
      public int getIbeaconMajor() {
        return ibeaconMajor_;
      }
      /**
       * <code>optional int32 ibeaconMajor = 2;</code>
       */
      public Builder setIbeaconMajor(int value) {
        bitField0_ |= 0x00000002;
        ibeaconMajor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ibeaconMajor = 2;</code>
       */
      public Builder clearIbeaconMajor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ibeaconMajor_ = 0;
        onChanged();
        return this;
      }

      // optional int64 hideHealthStatus = 3;
      private long hideHealthStatus_ ;
      /**
       * <code>optional int64 hideHealthStatus = 3;</code>
       */
      public boolean hasHideHealthStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 hideHealthStatus = 3;</code>
       */
      public long getHideHealthStatus() {
        return hideHealthStatus_;
      }
      /**
       * <code>optional int64 hideHealthStatus = 3;</code>
       */
      public Builder setHideHealthStatus(long value) {
        bitField0_ |= 0x00000004;
        hideHealthStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 hideHealthStatus = 3;</code>
       */
      public Builder clearHideHealthStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hideHealthStatus_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 incubationTimer = 4;
      private long incubationTimer_ ;
      /**
       * <code>optional int64 incubationTimer = 4;</code>
       */
      public boolean hasIncubationTimer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 incubationTimer = 4;</code>
       */
      public long getIncubationTimer() {
        return incubationTimer_;
      }
      /**
       * <code>optional int64 incubationTimer = 4;</code>
       */
      public Builder setIncubationTimer(long value) {
        bitField0_ |= 0x00000008;
        incubationTimer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 incubationTimer = 4;</code>
       */
      public Builder clearIncubationTimer() {
        bitField0_ = (bitField0_ & ~0x00000008);
        incubationTimer_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hmc.BaseFile1)
    }

    static {
      defaultInstance = new BaseFile1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hmc.BaseFile1)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hmc_BaseFile1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hmc_BaseFile1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016baseFile.proto\022\003hmc\"l\n\tBaseFile1\022\026\n\016in" +
      "fectedUserId\030\001 \003(\003\022\024\n\014ibeaconMajor\030\002 \001(\005" +
      "\022\030\n\020hideHealthStatus\030\003 \001(\003\022\027\n\017incubation" +
      "Timer\030\004 \001(\003B\030\n\026edu.umich.eecs.cooties"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hmc_BaseFile1_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hmc_BaseFile1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hmc_BaseFile1_descriptor,
              new java.lang.String[] { "InfectedUserId", "IbeaconMajor", "HideHealthStatus", "IncubationTimer", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
