// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playerAnnounce.proto

package edu.umich.eecs.cooties;

public final class PlayerAnnounce {
  private PlayerAnnounce() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerAnnounce1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 userId = 1;
    /**
     * <code>optional int64 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int64 userId = 1;</code>
     */
    long getUserId();

    // optional int32 minor = 2;
    /**
     * <code>optional int32 minor = 2;</code>
     */
    boolean hasMinor();
    /**
     * <code>optional int32 minor = 2;</code>
     */
    int getMinor();

    // optional string displayName = 3;
    /**
     * <code>optional string displayName = 3;</code>
     */
    boolean hasDisplayName();
    /**
     * <code>optional string displayName = 3;</code>
     */
    java.lang.String getDisplayName();
    /**
     * <code>optional string displayName = 3;</code>
     */
    com.google.protobuf.ByteString
        getDisplayNameBytes();

    // optional string hairType = 4;
    /**
     * <code>optional string hairType = 4;</code>
     */
    boolean hasHairType();
    /**
     * <code>optional string hairType = 4;</code>
     */
    java.lang.String getHairType();
    /**
     * <code>optional string hairType = 4;</code>
     */
    com.google.protobuf.ByteString
        getHairTypeBytes();

    // optional string skinType = 5;
    /**
     * <code>optional string skinType = 5;</code>
     */
    boolean hasSkinType();
    /**
     * <code>optional string skinType = 5;</code>
     */
    java.lang.String getSkinType();
    /**
     * <code>optional string skinType = 5;</code>
     */
    com.google.protobuf.ByteString
        getSkinTypeBytes();

    // optional string clothingType = 6;
    /**
     * <code>optional string clothingType = 6;</code>
     */
    boolean hasClothingType();
    /**
     * <code>optional string clothingType = 6;</code>
     */
    java.lang.String getClothingType();
    /**
     * <code>optional string clothingType = 6;</code>
     */
    com.google.protobuf.ByteString
        getClothingTypeBytes();

    // optional string hairColor = 7;
    /**
     * <code>optional string hairColor = 7;</code>
     */
    boolean hasHairColor();
    /**
     * <code>optional string hairColor = 7;</code>
     */
    java.lang.String getHairColor();
    /**
     * <code>optional string hairColor = 7;</code>
     */
    com.google.protobuf.ByteString
        getHairColorBytes();

    // optional string clothingColor = 8;
    /**
     * <code>optional string clothingColor = 8;</code>
     */
    boolean hasClothingColor();
    /**
     * <code>optional string clothingColor = 8;</code>
     */
    java.lang.String getClothingColor();
    /**
     * <code>optional string clothingColor = 8;</code>
     */
    com.google.protobuf.ByteString
        getClothingColorBytes();
  }
  /**
   * Protobuf type {@code hmc.PlayerAnnounce1}
   */
  public static final class PlayerAnnounce1 extends
      com.google.protobuf.GeneratedMessage
      implements PlayerAnnounce1OrBuilder {
    // Use PlayerAnnounce1.newBuilder() to construct.
    private PlayerAnnounce1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerAnnounce1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerAnnounce1 defaultInstance;
    public static PlayerAnnounce1 getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerAnnounce1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerAnnounce1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              minor_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              displayName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              hairType_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              skinType_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              clothingType_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              hairColor_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              clothingColor_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.eecs.cooties.PlayerAnnounce.internal_static_hmc_PlayerAnnounce1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.eecs.cooties.PlayerAnnounce.internal_static_hmc_PlayerAnnounce1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1.class, edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerAnnounce1> PARSER =
        new com.google.protobuf.AbstractParser<PlayerAnnounce1>() {
      public PlayerAnnounce1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerAnnounce1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerAnnounce1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>optional int64 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // optional int32 minor = 2;
    public static final int MINOR_FIELD_NUMBER = 2;
    private int minor_;
    /**
     * <code>optional int32 minor = 2;</code>
     */
    public boolean hasMinor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 minor = 2;</code>
     */
    public int getMinor() {
      return minor_;
    }

    // optional string displayName = 3;
    public static final int DISPLAYNAME_FIELD_NUMBER = 3;
    private java.lang.Object displayName_;
    /**
     * <code>optional string displayName = 3;</code>
     */
    public boolean hasDisplayName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string displayName = 3;</code>
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string displayName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string hairType = 4;
    public static final int HAIRTYPE_FIELD_NUMBER = 4;
    private java.lang.Object hairType_;
    /**
     * <code>optional string hairType = 4;</code>
     */
    public boolean hasHairType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string hairType = 4;</code>
     */
    public java.lang.String getHairType() {
      java.lang.Object ref = hairType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hairType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hairType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHairTypeBytes() {
      java.lang.Object ref = hairType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hairType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string skinType = 5;
    public static final int SKINTYPE_FIELD_NUMBER = 5;
    private java.lang.Object skinType_;
    /**
     * <code>optional string skinType = 5;</code>
     */
    public boolean hasSkinType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string skinType = 5;</code>
     */
    public java.lang.String getSkinType() {
      java.lang.Object ref = skinType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          skinType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string skinType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSkinTypeBytes() {
      java.lang.Object ref = skinType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skinType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string clothingType = 6;
    public static final int CLOTHINGTYPE_FIELD_NUMBER = 6;
    private java.lang.Object clothingType_;
    /**
     * <code>optional string clothingType = 6;</code>
     */
    public boolean hasClothingType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string clothingType = 6;</code>
     */
    public java.lang.String getClothingType() {
      java.lang.Object ref = clothingType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clothingType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clothingType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getClothingTypeBytes() {
      java.lang.Object ref = clothingType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clothingType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string hairColor = 7;
    public static final int HAIRCOLOR_FIELD_NUMBER = 7;
    private java.lang.Object hairColor_;
    /**
     * <code>optional string hairColor = 7;</code>
     */
    public boolean hasHairColor() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string hairColor = 7;</code>
     */
    public java.lang.String getHairColor() {
      java.lang.Object ref = hairColor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hairColor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hairColor = 7;</code>
     */
    public com.google.protobuf.ByteString
        getHairColorBytes() {
      java.lang.Object ref = hairColor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hairColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string clothingColor = 8;
    public static final int CLOTHINGCOLOR_FIELD_NUMBER = 8;
    private java.lang.Object clothingColor_;
    /**
     * <code>optional string clothingColor = 8;</code>
     */
    public boolean hasClothingColor() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string clothingColor = 8;</code>
     */
    public java.lang.String getClothingColor() {
      java.lang.Object ref = clothingColor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clothingColor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clothingColor = 8;</code>
     */
    public com.google.protobuf.ByteString
        getClothingColorBytes() {
      java.lang.Object ref = clothingColor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clothingColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = 0L;
      minor_ = 0;
      displayName_ = "";
      hairType_ = "";
      skinType_ = "";
      clothingType_ = "";
      hairColor_ = "";
      clothingColor_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, minor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDisplayNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getHairTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSkinTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getClothingTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getHairColorBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getClothingColorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDisplayNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getHairTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSkinTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getClothingTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getHairColorBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getClothingColorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hmc.PlayerAnnounce1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.eecs.cooties.PlayerAnnounce.internal_static_hmc_PlayerAnnounce1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.eecs.cooties.PlayerAnnounce.internal_static_hmc_PlayerAnnounce1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1.class, edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1.Builder.class);
      }

      // Construct using edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        minor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        displayName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        hairType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        skinType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        clothingType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        hairColor_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        clothingColor_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.eecs.cooties.PlayerAnnounce.internal_static_hmc_PlayerAnnounce1_descriptor;
      }

      public edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 getDefaultInstanceForType() {
        return edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1.getDefaultInstance();
      }

      public edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 build() {
        edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 buildPartial() {
        edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 result = new edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.minor_ = minor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.displayName_ = displayName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hairType_ = hairType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.skinType_ = skinType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.clothingType_ = clothingType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.hairColor_ = hairColor_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.clothingColor_ = clothingColor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1) {
          return mergeFrom((edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 other) {
        if (other == edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasMinor()) {
          setMinor(other.getMinor());
        }
        if (other.hasDisplayName()) {
          bitField0_ |= 0x00000004;
          displayName_ = other.displayName_;
          onChanged();
        }
        if (other.hasHairType()) {
          bitField0_ |= 0x00000008;
          hairType_ = other.hairType_;
          onChanged();
        }
        if (other.hasSkinType()) {
          bitField0_ |= 0x00000010;
          skinType_ = other.skinType_;
          onChanged();
        }
        if (other.hasClothingType()) {
          bitField0_ |= 0x00000020;
          clothingType_ = other.clothingType_;
          onChanged();
        }
        if (other.hasHairColor()) {
          bitField0_ |= 0x00000040;
          hairColor_ = other.hairColor_;
          onChanged();
        }
        if (other.hasClothingColor()) {
          bitField0_ |= 0x00000080;
          clothingColor_ = other.clothingColor_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umich.eecs.cooties.PlayerAnnounce.PlayerAnnounce1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 userId = 1;
      private long userId_ ;
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 minor = 2;
      private int minor_ ;
      /**
       * <code>optional int32 minor = 2;</code>
       */
      public boolean hasMinor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 minor = 2;</code>
       */
      public int getMinor() {
        return minor_;
      }
      /**
       * <code>optional int32 minor = 2;</code>
       */
      public Builder setMinor(int value) {
        bitField0_ |= 0x00000002;
        minor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 minor = 2;</code>
       */
      public Builder clearMinor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minor_ = 0;
        onChanged();
        return this;
      }

      // optional string displayName = 3;
      private java.lang.Object displayName_ = "";
      /**
       * <code>optional string displayName = 3;</code>
       */
      public boolean hasDisplayName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public java.lang.String getDisplayName() {
        java.lang.Object ref = displayName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          displayName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDisplayNameBytes() {
        java.lang.Object ref = displayName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displayName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public Builder setDisplayName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        displayName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public Builder clearDisplayName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        displayName_ = getDefaultInstance().getDisplayName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public Builder setDisplayNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        displayName_ = value;
        onChanged();
        return this;
      }

      // optional string hairType = 4;
      private java.lang.Object hairType_ = "";
      /**
       * <code>optional string hairType = 4;</code>
       */
      public boolean hasHairType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string hairType = 4;</code>
       */
      public java.lang.String getHairType() {
        java.lang.Object ref = hairType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hairType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hairType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHairTypeBytes() {
        java.lang.Object ref = hairType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hairType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hairType = 4;</code>
       */
      public Builder setHairType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        hairType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hairType = 4;</code>
       */
      public Builder clearHairType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hairType_ = getDefaultInstance().getHairType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hairType = 4;</code>
       */
      public Builder setHairTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        hairType_ = value;
        onChanged();
        return this;
      }

      // optional string skinType = 5;
      private java.lang.Object skinType_ = "";
      /**
       * <code>optional string skinType = 5;</code>
       */
      public boolean hasSkinType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string skinType = 5;</code>
       */
      public java.lang.String getSkinType() {
        java.lang.Object ref = skinType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          skinType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string skinType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSkinTypeBytes() {
        java.lang.Object ref = skinType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skinType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string skinType = 5;</code>
       */
      public Builder setSkinType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        skinType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string skinType = 5;</code>
       */
      public Builder clearSkinType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        skinType_ = getDefaultInstance().getSkinType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string skinType = 5;</code>
       */
      public Builder setSkinTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        skinType_ = value;
        onChanged();
        return this;
      }

      // optional string clothingType = 6;
      private java.lang.Object clothingType_ = "";
      /**
       * <code>optional string clothingType = 6;</code>
       */
      public boolean hasClothingType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string clothingType = 6;</code>
       */
      public java.lang.String getClothingType() {
        java.lang.Object ref = clothingType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clothingType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clothingType = 6;</code>
       */
      public com.google.protobuf.ByteString
          getClothingTypeBytes() {
        java.lang.Object ref = clothingType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clothingType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clothingType = 6;</code>
       */
      public Builder setClothingType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        clothingType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clothingType = 6;</code>
       */
      public Builder clearClothingType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        clothingType_ = getDefaultInstance().getClothingType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clothingType = 6;</code>
       */
      public Builder setClothingTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        clothingType_ = value;
        onChanged();
        return this;
      }

      // optional string hairColor = 7;
      private java.lang.Object hairColor_ = "";
      /**
       * <code>optional string hairColor = 7;</code>
       */
      public boolean hasHairColor() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string hairColor = 7;</code>
       */
      public java.lang.String getHairColor() {
        java.lang.Object ref = hairColor_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hairColor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hairColor = 7;</code>
       */
      public com.google.protobuf.ByteString
          getHairColorBytes() {
        java.lang.Object ref = hairColor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hairColor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hairColor = 7;</code>
       */
      public Builder setHairColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        hairColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hairColor = 7;</code>
       */
      public Builder clearHairColor() {
        bitField0_ = (bitField0_ & ~0x00000040);
        hairColor_ = getDefaultInstance().getHairColor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hairColor = 7;</code>
       */
      public Builder setHairColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        hairColor_ = value;
        onChanged();
        return this;
      }

      // optional string clothingColor = 8;
      private java.lang.Object clothingColor_ = "";
      /**
       * <code>optional string clothingColor = 8;</code>
       */
      public boolean hasClothingColor() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string clothingColor = 8;</code>
       */
      public java.lang.String getClothingColor() {
        java.lang.Object ref = clothingColor_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clothingColor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clothingColor = 8;</code>
       */
      public com.google.protobuf.ByteString
          getClothingColorBytes() {
        java.lang.Object ref = clothingColor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clothingColor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clothingColor = 8;</code>
       */
      public Builder setClothingColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        clothingColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clothingColor = 8;</code>
       */
      public Builder clearClothingColor() {
        bitField0_ = (bitField0_ & ~0x00000080);
        clothingColor_ = getDefaultInstance().getClothingColor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clothingColor = 8;</code>
       */
      public Builder setClothingColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        clothingColor_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hmc.PlayerAnnounce1)
    }

    static {
      defaultInstance = new PlayerAnnounce1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hmc.PlayerAnnounce1)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hmc_PlayerAnnounce1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hmc_PlayerAnnounce1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024playerAnnounce.proto\022\003hmc\"\251\001\n\017PlayerAn" +
      "nounce1\022\016\n\006userId\030\001 \001(\003\022\r\n\005minor\030\002 \001(\005\022\023" +
      "\n\013displayName\030\003 \001(\t\022\020\n\010hairType\030\004 \001(\t\022\020\n" +
      "\010skinType\030\005 \001(\t\022\024\n\014clothingType\030\006 \001(\t\022\021\n" +
      "\thairColor\030\007 \001(\t\022\025\n\rclothingColor\030\010 \001(\tB" +
      "\030\n\026edu.umich.eecs.cooties"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hmc_PlayerAnnounce1_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hmc_PlayerAnnounce1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hmc_PlayerAnnounce1_descriptor,
              new java.lang.String[] { "UserId", "Minor", "DisplayName", "HairType", "SkinType", "ClothingType", "HairColor", "ClothingColor", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
