// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touch.proto

package edu.umich.eecs.cooties;

public final class Touch {
  private Touch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Touch1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 timestamp = 1;
    /**
     * <code>optional int64 timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 1;</code>
     */
    long getTimestamp();

    // optional bool infected = 2;
    /**
     * <code>optional bool infected = 2;</code>
     */
    boolean hasInfected();
    /**
     * <code>optional bool infected = 2;</code>
     */
    boolean getInfected();

    // optional bool incubation = 3;
    /**
     * <code>optional bool incubation = 3;</code>
     */
    boolean hasIncubation();
    /**
     * <code>optional bool incubation = 3;</code>
     */
    boolean getIncubation();

    // optional int64 sourceUserId = 4;
    /**
     * <code>optional int64 sourceUserId = 4;</code>
     */
    boolean hasSourceUserId();
    /**
     * <code>optional int64 sourceUserId = 4;</code>
     */
    long getSourceUserId();

    // optional int64 targetUserId = 5;
    /**
     * <code>optional int64 targetUserId = 5;</code>
     */
    boolean hasTargetUserId();
    /**
     * <code>optional int64 targetUserId = 5;</code>
     */
    long getTargetUserId();
  }
  /**
   * Protobuf type {@code hmc.Touch1}
   */
  public static final class Touch1 extends
      com.google.protobuf.GeneratedMessage
      implements Touch1OrBuilder {
    // Use Touch1.newBuilder() to construct.
    private Touch1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Touch1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Touch1 defaultInstance;
    public static Touch1 getDefaultInstance() {
      return defaultInstance;
    }

    public Touch1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Touch1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              infected_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              incubation_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sourceUserId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              targetUserId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.eecs.cooties.Touch.internal_static_hmc_Touch1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.eecs.cooties.Touch.internal_static_hmc_Touch1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umich.eecs.cooties.Touch.Touch1.class, edu.umich.eecs.cooties.Touch.Touch1.Builder.class);
    }

    public static com.google.protobuf.Parser<Touch1> PARSER =
        new com.google.protobuf.AbstractParser<Touch1>() {
      public Touch1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Touch1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Touch1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional bool infected = 2;
    public static final int INFECTED_FIELD_NUMBER = 2;
    private boolean infected_;
    /**
     * <code>optional bool infected = 2;</code>
     */
    public boolean hasInfected() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool infected = 2;</code>
     */
    public boolean getInfected() {
      return infected_;
    }

    // optional bool incubation = 3;
    public static final int INCUBATION_FIELD_NUMBER = 3;
    private boolean incubation_;
    /**
     * <code>optional bool incubation = 3;</code>
     */
    public boolean hasIncubation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool incubation = 3;</code>
     */
    public boolean getIncubation() {
      return incubation_;
    }

    // optional int64 sourceUserId = 4;
    public static final int SOURCEUSERID_FIELD_NUMBER = 4;
    private long sourceUserId_;
    /**
     * <code>optional int64 sourceUserId = 4;</code>
     */
    public boolean hasSourceUserId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 sourceUserId = 4;</code>
     */
    public long getSourceUserId() {
      return sourceUserId_;
    }

    // optional int64 targetUserId = 5;
    public static final int TARGETUSERID_FIELD_NUMBER = 5;
    private long targetUserId_;
    /**
     * <code>optional int64 targetUserId = 5;</code>
     */
    public boolean hasTargetUserId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 targetUserId = 5;</code>
     */
    public long getTargetUserId() {
      return targetUserId_;
    }

    private void initFields() {
      timestamp_ = 0L;
      infected_ = false;
      incubation_ = false;
      sourceUserId_ = 0L;
      targetUserId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, infected_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, incubation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, sourceUserId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, targetUserId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, infected_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, incubation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, sourceUserId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, targetUserId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.umich.eecs.cooties.Touch.Touch1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.eecs.cooties.Touch.Touch1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.eecs.cooties.Touch.Touch1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hmc.Touch1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.eecs.cooties.Touch.Touch1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.eecs.cooties.Touch.internal_static_hmc_Touch1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.eecs.cooties.Touch.internal_static_hmc_Touch1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umich.eecs.cooties.Touch.Touch1.class, edu.umich.eecs.cooties.Touch.Touch1.Builder.class);
      }

      // Construct using edu.umich.eecs.cooties.Touch.Touch1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        infected_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        incubation_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        sourceUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        targetUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.eecs.cooties.Touch.internal_static_hmc_Touch1_descriptor;
      }

      public edu.umich.eecs.cooties.Touch.Touch1 getDefaultInstanceForType() {
        return edu.umich.eecs.cooties.Touch.Touch1.getDefaultInstance();
      }

      public edu.umich.eecs.cooties.Touch.Touch1 build() {
        edu.umich.eecs.cooties.Touch.Touch1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umich.eecs.cooties.Touch.Touch1 buildPartial() {
        edu.umich.eecs.cooties.Touch.Touch1 result = new edu.umich.eecs.cooties.Touch.Touch1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.infected_ = infected_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.incubation_ = incubation_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sourceUserId_ = sourceUserId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.targetUserId_ = targetUserId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.eecs.cooties.Touch.Touch1) {
          return mergeFrom((edu.umich.eecs.cooties.Touch.Touch1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umich.eecs.cooties.Touch.Touch1 other) {
        if (other == edu.umich.eecs.cooties.Touch.Touch1.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasInfected()) {
          setInfected(other.getInfected());
        }
        if (other.hasIncubation()) {
          setIncubation(other.getIncubation());
        }
        if (other.hasSourceUserId()) {
          setSourceUserId(other.getSourceUserId());
        }
        if (other.hasTargetUserId()) {
          setTargetUserId(other.getTargetUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umich.eecs.cooties.Touch.Touch1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umich.eecs.cooties.Touch.Touch1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 timestamp = 1;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional bool infected = 2;
      private boolean infected_ ;
      /**
       * <code>optional bool infected = 2;</code>
       */
      public boolean hasInfected() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool infected = 2;</code>
       */
      public boolean getInfected() {
        return infected_;
      }
      /**
       * <code>optional bool infected = 2;</code>
       */
      public Builder setInfected(boolean value) {
        bitField0_ |= 0x00000002;
        infected_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool infected = 2;</code>
       */
      public Builder clearInfected() {
        bitField0_ = (bitField0_ & ~0x00000002);
        infected_ = false;
        onChanged();
        return this;
      }

      // optional bool incubation = 3;
      private boolean incubation_ ;
      /**
       * <code>optional bool incubation = 3;</code>
       */
      public boolean hasIncubation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool incubation = 3;</code>
       */
      public boolean getIncubation() {
        return incubation_;
      }
      /**
       * <code>optional bool incubation = 3;</code>
       */
      public Builder setIncubation(boolean value) {
        bitField0_ |= 0x00000004;
        incubation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool incubation = 3;</code>
       */
      public Builder clearIncubation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        incubation_ = false;
        onChanged();
        return this;
      }

      // optional int64 sourceUserId = 4;
      private long sourceUserId_ ;
      /**
       * <code>optional int64 sourceUserId = 4;</code>
       */
      public boolean hasSourceUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 sourceUserId = 4;</code>
       */
      public long getSourceUserId() {
        return sourceUserId_;
      }
      /**
       * <code>optional int64 sourceUserId = 4;</code>
       */
      public Builder setSourceUserId(long value) {
        bitField0_ |= 0x00000008;
        sourceUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sourceUserId = 4;</code>
       */
      public Builder clearSourceUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sourceUserId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 targetUserId = 5;
      private long targetUserId_ ;
      /**
       * <code>optional int64 targetUserId = 5;</code>
       */
      public boolean hasTargetUserId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 targetUserId = 5;</code>
       */
      public long getTargetUserId() {
        return targetUserId_;
      }
      /**
       * <code>optional int64 targetUserId = 5;</code>
       */
      public Builder setTargetUserId(long value) {
        bitField0_ |= 0x00000010;
        targetUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 targetUserId = 5;</code>
       */
      public Builder clearTargetUserId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        targetUserId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hmc.Touch1)
    }

    static {
      defaultInstance = new Touch1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hmc.Touch1)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hmc_Touch1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hmc_Touch1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013touch.proto\022\003hmc\"m\n\006Touch1\022\021\n\ttimestam" +
      "p\030\001 \001(\003\022\020\n\010infected\030\002 \001(\010\022\022\n\nincubation\030" +
      "\003 \001(\010\022\024\n\014sourceUserId\030\004 \001(\003\022\024\n\014targetUse" +
      "rId\030\005 \001(\003B\030\n\026edu.umich.eecs.cooties"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hmc_Touch1_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hmc_Touch1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hmc_Touch1_descriptor,
              new java.lang.String[] { "Timestamp", "Infected", "Incubation", "SourceUserId", "TargetUserId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
